# 控制点击部分的坐标
# 坐标X和Y归一化到[0, 1]，以便适用于不同大小的窗口

# 同意
CONTINUOUS_BATTLE_BUTTON_AGREE_X = 697
CONTINUOUS_BATTLE_BUTTON_AGREE_Y = 447
# cat
CONTINUOUS_BATTLE_BUTTON_AGREE_CAT_START_X = 100
CONTINUOUS_BATTLE_BUTTON_AGREE_CAT_END_X = 890
CONTINUOUS_BATTLE_BUTTON_AGREE_CAT_START_Y = 400
CONTINUOUS_BATTLE_BUTTON_AGREE_CAT_END_Y = 480

# 我的
CONTINUOUS_BATTLE_BUTTON_MY_X = 800
CONTINUOUS_BATTLE_BUTTON_MY_Y = 506

# 登录
CONTINUOUS_BATTLE_BUTTON_LOGIN_X = 480
CONTINUOUS_BATTLE_BUTTON_LOGIN_Y = 200

# 输入
CONTINUOUS_BATTLE_BUTTON_INPUT_USERNAME_CLEAR_X = 892
CONTINUOUS_BATTLE_BUTTON_INPUT_USERNAME_CLEAR_Y = 309
CONTINUOUS_BATTLE_BUTTON_INPUT_PASSWORD_CLEAR_X = 844
CONTINUOUS_BATTLE_BUTTON_INPUT_PASSWORD_CLEAR_Y = 381

CONTINUOUS_BATTLE_BUTTON_INPUT_USERNAME_X = 200
CONTINUOUS_BATTLE_BUTTON_INPUT_USERNAME_Y = 313
CONTINUOUS_BATTLE_BUTTON_INPUT_PASSWORD_X = 200
CONTINUOUS_BATTLE_BUTTON_INPUT_PASSWORD_Y = 380

# 向上滑动
CONTINUOUS_BATTLE_SWIPE_START_X=0
CONTINUOUS_BATTLE_SWIPE_START_Y=450
CONTINUOUS_BATTLE_SWIPE_END_X=0
CONTINUOUS_BATTLE_SWIPE_END_Y=0
# 提交
CONTINUOUS_BATTLE_BUTTON_INPUT_SUBMIT_X = 500
CONTINUOUS_BATTLE_BUTTON_INPUT_SUBMIT_Y = 313
# 单位管理
CONTINUOUS_BATTLE_BUTTON_INPUT_MANAGER_X = 95
CONTINUOUS_BATTLE_BUTTON_INPUT_MANAGER_Y = 511

# 保存
CONTINUOUS_BATTLE_BUTTON_INPUT_SAVE_X = 700
CONTINUOUS_BATTLE_BUTTON_INPUT_SAVE_Y = 427

# 培训考核
CONTINUOUS_BATTLE_BUTTON_INPUT_KAOHE_X = 800
CONTINUOUS_BATTLE_BUTTON_INPUT_KAOHE_Y = 330

# 新办必学
CONTINUOUS_BATTLE_BUTTON_INPUT_XINBANBIXUE_X = 300
CONTINUOUS_BATTLE_BUTTON_INPUT_XINBANBIXUE_Y = 206

# 列表
# 向上滑动
CONTINUOUS_BATTLE_SWIPE_LIEBIAO_START_X=0
CONTINUOUS_BATTLE_SWIPE_LIEBIAO_START_Y=300
CONTINUOUS_BATTLE_SWIPE_LIEBIAO_END_X=0
CONTINUOUS_BATTLE_SWIPE_LIEBIAO_END_Y=77
# 返回
CONTINUOUS_BATTLE_BUTTON_BACK_X = 24
CONTINUOUS_BATTLE_BUTTON_BACK_Y = 73
# 点击列表
CONTINUOUS_BATTLE_BUTTON_LIEBIAO_X = 469
CONTINUOUS_BATTLE_BUTTON_LIEBIAO_Y = 300

# 截屏
CONTINUOUS_SCREENCAP_START_X=0
CONTINUOUS_SCREENCAP_START_Y=109
CONTINUOUS_SCREENCAP_END_X=228
CONTINUOUS_SCREENCAP_END_Y=167

# 登出
CONTINUOUS_BATTLE_BUTTON_LOGOUT_X = 936
CONTINUOUS_BATTLE_BUTTON_LOGOUT_Y = 84